# Generated by Django 2.1.5 on 2020-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_confirmemailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Внешний ИД'),
        ),
    ]
